# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5678d376bfdbc7cc2570400d2883362dd673b343c8ece428f3ef4994d07d36b1d061cf93b140a8ec9916d8134d84a99804de400048285321067f61b62717cbf

test:
  secret_key_base: dbdb9dd3a344aa9f13ed047f3734d45f2f298802b9a4ca74d40f00856875688732970935a71f27e2c2c5be1a21d463825d37ae7ea222ba79a5d1430b4b589391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
